title: <p align="center"> Alex Harrods </p>

logo: /assets/pics/IMG_20200911_122230_1-photoaidcom-cropped.jpg

description:
  <p align="center">
  <a href="pdf/Resume Alex Harrods (Tatyana Okoneshnikova).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/alex-harrods/">LinkedIn</a> |
  <a href="https://github.com/AlexHarrods">GitHub</a>
  </p>
  
  <p align="left">
  I recently completed a certification in Data Analytics and have one year of hands-on experience in data preparation and analysis, dashboard development along with over 15 years in project management and educational program design.
 
  
theme: jekyll-theme-minimal
