title: <p align="center"> Alex Harrods </p>

logo: /assets/pics/IMG_20200911_122230_1-photoaidcom-cropped.jpg

description:
  <p align="center">
  <a href="pdf/Alex Harrods Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/alex-harrods/">LinkedIn</a> |
  <a href="https://github.com/AlexHarrods">GitHub</a>
  </p>
  
  <p align="justify">
  Instructional design and project management background (15+ years professional experience)
  <br><br>
  Transitioned to Data Analytics in January 2023
  <br><br>
  </p>

theme: jekyll-theme-minimal
